FROM openjdk:8-jdk-alpine

# Two commands which are required for divio cloud
RUN echo "#!/bin/sh" > /usr/local/bin/start && chmod +x /usr/local/bin/start
COPY migrate.sh /app/migrate.sh

# Expose the port
EXPOSE 8080

CMD ["/app/mvnw", "spring-boot:run"]


